### ISSUE TITLE
Content-Type issues with Edge and Firefox

### ISSUE THREAD

**Issue by peternoyes** [shurcooL/httpgzip#1]
This library relies on the underlying http.ServeContent function call to choose a Mime-Type. When http.ServeContent comes across a file for which it doesn't recognize the extension, it tries to examine the file contents to determine the type. For zipped contents, it always finds chooses 'application/x-gzip'

The problem with sending down the type as application/x-gzip is that Firefox and Microsoft Edge will not decompress the stream in an AJAX call because it is guessing that the user wants the data to stay compressed. Chrome decompresses the data always it seems.

Markdown (.md) files are a type that falls into the category.

**Comment by dmitshur** [comment]
Thank you so much for reporting this issue @peternoyes! This looks like a valid bug in `httpgzip`.

At first glance, I think this issue is very fixable and I have an idea how to do that. I will try it out soon.

> When http.ServeContent comes across a file for which it doesn't recognize the extension [...] Markdown (.md) files are a type that falls into the category.

Funny, because I absolutely ran into that too... 😉 See [here](https://github.com/shurcooL/home/blob/2c3625aaf6d715a934620ed2fb386005d463fcee/main.go#L29).

**Comment by peternoyes** [comment]
No problem!

I have a potential fix on my fork of the project

**Comment by peternoyes** [comment]
Even with my fix there is a still a problem. I am using the Gopherpen template. My fix only solves the problem in development (go build -tags=dev). When 'go generate' runs and statically embeds the assets, the content-type goes back to application/x-gzip for a lot of things.

**Comment by dmitshur** [comment]
Okay, so the problem is fully isolated to the current [`httpgzip.ServeContent`](https://gotools.org/github.com/shurcooL/httpgzip?rev=912c9efe4160d7c7ab6dc44ab4c9a0eac5ec0716#ServeContent) implementation.

It can be reasoned about on a high level.

The input is a normal `content io.ReadSeeker`. `httpgzip.ServeContent` tries to gzip compress, in situations where it's possible, as efficiently as it can. Then, it passes off the serving of compressed content to [`http.ServeContent`](https://godoc.org/net/http#ServeContent).

`http.ServeContent` is documented to:

> If the response's Content-Type header is not set, ServeContent first tries to deduce the type from name's file extension and, if that fails, falls back to reading the first block of the content and passing it to DetectContentType. The name is otherwise unused; in particular it can be empty and is never sent in the response.

However, if we give it compressed content, [`http.DetectContentType`](https://godoc.org/net/http#DetectContentType) will not try to decompress it to figure out the original content type. It's going to operate on the bytes as is, and return `application/x-gzip`.

So the clear resolution to this bug is that `httpgzip.ServeContent`, in situations where it serves gzip compressed content via `http.ServeContent`, must first detect the content type and set the Content-Type header (if it's not already set).

> Even with my fix there is a still a problem.

If you're referring to commit https://github.com/peternoyes/httpgzip/commit/ea289bd62bf137ae0a79c7a11e7a312e58729f99, the issue there is that you didn't intercept one of the two possible paths that serve gzip compressed content.

There are two:
1. https://gotools.org/github.com/shurcooL/httpgzip?rev=912c9efe4160d7c7ab6dc44ab4c9a0eac5ec0716#gzip.go-L48-L49
2. https://gotools.org/github.com/shurcooL/httpgzip?rev=912c9efe4160d7c7ab6dc44ab4c9a0eac5ec0716#gzip.go-L55-L56

You've only taken care of the second but not the first.

I'll make a PR that resolves this soon.
