### ISSUE TITLE
missing node "golang.org/x/net/lex/httplex" for "github.com/shurcooL/httpgzip"

### ISSUE THREAD

**Issue by h8liu** [shurcooL/httpgzip#5]
httplex has renamed/merged into httpguts

https://github.com/golang/net/commit/cbb82b59bc5199680c5bf34109e12097095dca9b

breakage (again) detected by [smallrepo.com](https://smallrepo.com)

build log: https://smallrepo.com/builds/20180507-191159-c59746e5

**Comment by h8liu** [comment]
dear Dmitri, will you subscribe if I make this an automatic service to your email?

**Comment by dmitshur** [comment]
Thanks for reporting Lonnie.

> dear Dmitri, will you subscribe if I make this an automatic service to your email?

I’ll need to think about it, but most likely yes.

**Comment by h8liu** [comment]
:)

> I’ll need to think about it, but most likely yes.

working on it! stay tuned!

**Comment by dmitshur** [comment]
@h8liu I've merged the fix into `master` by now, but I see that current builds on smallrepo.com (as recent as 4 minutes ago) are still using the `smlrepo` fork:

https://smallrepo.com/builds/20180508-005559-ff953b37

```
2018/05/08 00:56:56 using "https://github.com/smlrepo/httpgzip.git" for "github.com/shurcooL/httpgzip"
```

```
"RepoFixes": {
  ...
  "github.com/shurcooL/httpgzip": "https://github.com/smlrepo/httpgzip.git"
}
```

Is it a manual process to remove the repo override, since it's no longer needed? Or will it happen automatically after some more time passes?

**Comment by h8liu** [comment]
ha, good question

it is a manually process for now, but we are working on making it hopefully smarter.
